/// Generated by Flutter GetX Starter on 2022-10-17 03:08
import 'package:ejarkom/app/Ads/ads/widget/ads_requests/widget/action_dialog.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

import 'ads_requests_logic.dart';
import 'ads_requests_state.dart';

class AdsRequestsView extends StatefulWidget {
  @override
  _AdsRequestsViewState createState() => _AdsRequestsViewState();
}

class _AdsRequestsViewState extends State<AdsRequestsView> {
  final AdsRequestsLogic logic = Get.find<AdsRequestsLogic>();
  final AdsRequestsState state = Get.find<AdsRequestsLogic>().state;

  @override
  void dispose() {
    Get.delete<AdsRequestsLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text(
          'All Requests'.tr,
          style: Get.textTheme.bodyText1!.copyWith(
            color: Get.theme.primaryColor,
          ),
        ),
        leading: IconButton(
          onPressed: () {
            Get.back();
          },
          icon: Icon(
            Icons.arrow_back_ios,
            color: Get.theme.primaryColor,
          ),
        ),
      ),
      body: Center(
        child: Obx(
          () => state.gettingState.value
              ? MyIndicator()
              : state.requests.isEmpty
                  ? Text(
                      'No Requests Yet'.tr,
                      style: Get.textTheme.bodyText1,
                    )
                  : Padding(
                      padding: EdgeInsets.symmetric(
                          horizontal: 20.w, vertical: 10.h),
                      child: ListView.builder(
                        itemCount: state.requests.length,
                        itemBuilder: (BuildContext context, int index) {
                          return Padding(
                            padding: EdgeInsets.symmetric(vertical: 10.h),
                            child: Container(
                              // height: 200.h,
                              width: Get.width.w,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(5.sp),
                                border: Border.all(color: Colors.grey),
                              ),
                              child: Padding(
                                padding: EdgeInsets.symmetric(
                                  horizontal: 10.w,
                                  vertical: 10.h,
                                ),
                                child: Column(
                                  children: [
                                    // Row(
                                    //   mainAxisAlignment:
                                    //       MainAxisAlignment.spaceBetween,
                                    //   children: [
                                    //     ElevatedButton(
                                    //       onPressed: () {
                                    //         Get.dialog(
                                    //           CheckDialog(),
                                    //           barrierDismissible: false,
                                    //         );
                                    //       },
                                    //       child: Text(
                                    //         'Check '.tr,
                                    //       ),
                                    //     ),
                                    //     getState(
                                    //         s: state
                                    //             .requests[index].reqestStatus!),
                                    //   ],
                                    // ),
                                    SizedBox(height: 10.h),
                                    Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                      children: [
                                        Text(
                                          'Name:'.tr,
                                          style:
                                              Get.textTheme.bodyText1!.copyWith(
                                            fontSize: 19.sp,
                                          ),
                                        ),
                                        Text(
                                          state.requests[index].name!,
                                          style: Get.textTheme.bodyText1,
                                        ),
                                      ],
                                    ),
                                    SizedBox(height: 10.h),
                                    // Row(
                                    //   mainAxisAlignment:
                                    //       MainAxisAlignment.spaceBetween,
                                    //   children: [
                                    //     Text(
                                    //       'Phone:'.tr,
                                    //       style:
                                    //           Get.textTheme.bodyText1!.copyWith(
                                    //         fontSize: 19.sp,
                                    //       ),
                                    //     ),
                                    //     Text(
                                    //       state.requests[index].phone!,
                                    //       style: Get.textTheme.bodyText1,
                                    //     ),
                                    //   ],
                                    // ),
                                    // SizedBox(height: 10.h),
                                    // Row(
                                    //   mainAxisAlignment:
                                    //       MainAxisAlignment.spaceBetween,
                                    //   children: [
                                    //     Text(
                                    //       'E-mail:'.tr,
                                    //       style:
                                    //           Get.textTheme.bodyText1!.copyWith(
                                    //         fontSize: 19.sp,
                                    //       ),
                                    //     ),
                                    //     Text(
                                    //       state.requests[index].email!,
                                    //       style: Get.textTheme.bodyText1,
                                    //     ),
                                    //   ],
                                    // ),
                                    SizedBox(height: 10.h),
                                    SizedBox(height: 10.h),
                                    Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                      children: [
                                        ElevatedButton(
                                          onPressed: () {
                                            Get.dialog(
                                              MyActionDialog(type: 'reject'),
                                              barrierDismissible: false,
                                            );
                                          },
                                          child: Text(
                                            'Reject'.tr,
                                          ),
                                        ),
                                        ElevatedButton(
                                          onPressed: () {
                                            // logic.actionDialog(type: 'Accept');
                                            Get.dialog(
                                              MyActionDialog(type: 'Accept'),
                                              barrierDismissible: false,
                                            );
                                          },
                                          child: Text(
                                            'Accept'.tr,
                                          ),
                                        ),
                                      ],
                                    )
                                  ],
                                ),
                              ),
                            ),
                          );
                        },
                      ),
                    ),
        ),
      ),
    );
  }

  Widget getState({required String s}) {
    print(s);
    if (s == 'Waiting') {
      return Container(
        height: 40.h,
        width: 150.h,
        decoration: BoxDecoration(
            color: Colors.amber.withOpacity(0.6),
            borderRadius: BorderRadius.circular(8.sp)),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Waiting....'.tr,
                style: Get.theme.textTheme.bodyText1!.copyWith(
                  color: Colors.black38,
                  fontSize: 19.sp,
                ),
              ),
              const Icon(
                Icons.timer,
                color: Colors.black38,
              )
            ],
          ),
        ),
      );
    } else if (s == 'Accept') {
      return Container(
        height: 40.h,
        width: 150.h,
        decoration: BoxDecoration(
            color: Colors.green.withOpacity(0.6),
            borderRadius: BorderRadius.circular(8.sp)),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Accepted'.tr,
                style: Get.theme.textTheme.bodyText1!.copyWith(
                  color: Colors.white,
                  fontSize: 19.sp,
                ),
              ),
              Icon(
                Icons.check,
                color: Colors.white,
              )
            ],
          ),
        ),
      );
    } else {
      return Container(
        height: 40.h,
        width: 150.h,
        decoration: BoxDecoration(
            color: Colors.red.withOpacity(0.6),
            borderRadius: BorderRadius.circular(8.sp)),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Rejected'.tr,
                style: Get.theme.textTheme.bodyText1!.copyWith(
                  color: Colors.white,
                  fontSize: 19.sp,
                ),
              ),
              Icon(
                Icons.close,
                color: Colors.white,
              )
            ],
          ),
        ),
      );
    }
  }
}
