/// Generated by Flutter GetX Starter on 2022-10-16 04:41
import 'package:ejarkom/app/services/models/my_ser_model/my_ser_model.dart';
import 'package:ejarkom/utils/apis.dart';
import 'package:get/get.dart';

import 'finished_services_state.dart';

class FinishedServicesLogic extends GetxController {
  final state = FinishedServicesState();
  void changePageState() =>
      state.gettingState.value = !state.gettingState.value;

  void getPage() async {
    changePageState();
    var result = await state.servicesHttp.getServices(api: myReadyServices);
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changePageState();
  }

  void pageDone(MySerModel myserves) {
    state.services = myserves.myserves!;
  }

  void pageError(String e) {
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}