import 'dart:io';

import 'package:ejarkom/app/Ads/models/GetCityModel.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../utils/http_manager/create_ad_http.dart';
import '../../Ads/models/GetBuildTypeModel.dart';
import '../../Ads/models/Zone.dart';

/// Generated by Flutter GetX Starter on 2022-10-18 23:47
class AddBuildManageState {
  AddBuildManageState() {
    nameE = TextEditingController();

    descriptionE = TextEditingController();

    addressE = TextEditingController();

    cost = TextEditingController();
    phone = TextEditingController();

    video = TextEditingController();
    formKey = GlobalKey<FormState>();
    cities = [];
    zones = [];
    typeBuilds = [];
    createAdHttp = CreateAdHttp();
  }
  RxInt cureentIndex=0.obs;

  late TextEditingController nameE;

  late TextEditingController descriptionE;

  late TextEditingController addressE;

  late TextEditingController cost;

  late TextEditingController phone;
  late TextEditingController video;
  late List<City> cities;
  late List<Zone> zones;
  RxBool gettingCities = false.obs;
  RxBool gettingZones = false.obs;
  RxBool gettingBuildTypes = false.obs;
  RxBool createAdsState = false.obs;

  late List<TypeBuild> typeBuilds;
  late CreateAdHttp createAdHttp;
  City? selectedCity;
  Zone? selectedZone;
  TypeBuild? selectedBuildType;
  List<File> images = [];
  List<Uint8List> photos = [];
  PageController pageController = PageController();

  late final formKey;
}
