/// Generated by Flutter GetX Starter on 2022-10-16 04:58
import 'package:ejarkom/app/complete_data/models/MyDataModel.dart';
import 'package:get/get.dart';

import 'my_data_view_state.dart';

class MyDataViewLogic extends GetxController {
  final state = MyDataViewState();
  void changeGetState()=>state.getState.value=!state.getState.value;




  void getPage() async {
    changeGetState();
    var result = await state.rentHttp.getMyData();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changeGetState();
  }

  void pageDone(MyDataModel myserves) {
    state.myData = myserves.myData!;
  }

  void pageError(String e) {
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}