/// Generated by Flutter GetX Starter on 2022-10-16 04:58
import 'dart:convert';

import 'package:ejarkom/app/complete_data/models/MyDataModel.dart';
import 'package:ejarkom/utils/my_database.dart';
import 'package:ejarkom/utils/push.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:pusher_channels_flutter/pusher_channels_flutter.dart';

import 'my_data_view_state.dart';

class MyDataViewLogic extends GetxController {
  final state = MyDataViewState();
  void changeGetState() => state.getState.value = !state.getState.value;

  void getPage() async {
    changeGetState();
    var result = await state.rentHttp.getMyData();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changeGetState();
  }
  void updatePage()async{
    var result = await state.rentHttp.getMyData();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    update();
  }

  void pageDone(MyDataModel myserves) {
    state.myData = myserves.myData!;
  }


  String dateParser(String date) {
    return DateFormat('yyyy-MM-dd – h:mm a').format(DateTime.parse(date));
  }


   Future<void> newPusher() async {
    PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();
    try {
      await pusher.init(
          apiKey: key,
          cluster: cluster,
          onConnectionStateChange: (String? c, String? v) {},
          onError: (String? v, int? a, dynamic b) {},
          onSubscriptionSucceeded: (String? c, dynamic b) {},
          onEvent: (event) {
            // print(jsonDecode(event.data.toString()));

            if (event.eventName != 'pusher:pong') {
              var formatedData = jsonDecode(event.data);
              var id = MyDataBase.getId();
              print(event.eventName);
              // print(formatedData);


              if (formatedData['id'] == id) {
                print(event.eventName);
                if (event.eventName.contains('user_data')) {
                  // infoNotiiftcaion();

                  updatePage();
                }
                
              }

              // print(event.data);
            }
          });
      await pusher.subscribe(channelName: 'user');
      await pusher.connect();
    } catch (e) {
      print("ERROR: $e");
    }
  }




  void pageError(String e) {
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
    newPusher();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
