import 'package:ejarkom/app/complete_data/models/MyDataModel.dart';
import 'package:ejarkom/utils/http_manager/rent_http.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-16 04:58
class MyDataViewState {
  MyDataViewState() {
    rentHttp=RentHttp();
    myData=[];
  }
  late RentHttp rentHttp;
  RxBool getState=false.obs;
  late List<MyData>myData;
}
