import 'dart:io';

import 'package:ejarkom/app/Ads/models/GetBuildTypeModel.dart';
import 'package:ejarkom/app/Ads/models/GetCityModel.dart';
import 'package:ejarkom/app/Ads/models/Zone.dart';
import 'package:ejarkom/utils/http_manager/create_ad_http.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-09 19:24
class CreateAdsState {
  CreateAdsState() {
    nameE = TextEditingController();
    nameA = TextEditingController();
    descriptionE = TextEditingController();
    descriptionA = TextEditingController();
    addressE = TextEditingController();
    addressA = TextEditingController();
    cost = TextEditingController();
    numOfRooms = TextEditingController();
    numOfBath = TextEditingController();
    video = TextEditingController();
    formKey = GlobalKey<FormState>();
    cities = [];
    zones = [];
    typeBuilds = [];
    createAdHttp = CreateAdHttp();
  }
  late TextEditingController nameE;
  late TextEditingController nameA;
  late TextEditingController descriptionE;
  late TextEditingController descriptionA;
  late TextEditingController addressE;
  late TextEditingController addressA;
  late TextEditingController cost;
  late TextEditingController numOfRooms;
  late TextEditingController numOfBath;
  late TextEditingController video;
  List<String> costTypes = [
    'Monthly'.tr,
    'Weekly'.tr,
    'Annually'.tr,
  ];
  String? selectedCostType;
  late List<City> cities;
  late List<Zone> zones;
  RxBool gettingCities = false.obs;
  RxBool gettingZones = false.obs;
  RxBool gettingBuildTypes = false.obs;
  RxBool createAdsState = false.obs;

  late List<TypeBuild> typeBuilds;
  late CreateAdHttp createAdHttp;
  City? selectedCity;
  Zone? selectedZone;
  TypeBuild? selectedBuildType;
  List<File> images = [];
  List<Uint8List> photos = [];
  PageController pageController = PageController();

  late final formKey;
}
