/// Generated by Flutter GetX Starter on 2022-10-09 19:24
import 'dart:io';

import 'package:ejarkom/app/Ads/create_ads/widgets/info_dialog.dart';
import 'package:ejarkom/app/Ads/create_ads/widgets/packs_ex_dialog.dart';
import 'package:ejarkom/app/Ads/models/CreateAdModel.dart';
import 'package:ejarkom/app/Ads/models/GetBuildTypeModel.dart';
import 'package:ejarkom/app/Ads/models/Zone.dart';
import 'package:ejarkom/utils/http_manager/create_ad_http.dart';
import 'package:ejarkom/utils/method.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/animation.dart';
import 'package:get/get.dart';

import '../models/GetCityModel.dart';
import 'create_ads_state.dart';

class CreateAdsLogic extends GetxController {
  final state = CreateAdsState();

  void changePageStat(int state1) {
    if (state1 == 1) {
      if (state.images.isEmpty) {
      } else {
        state.currentPageState.value = state1;
        state.mainPage.animateToPage(
          1,
          duration: Duration(milliseconds: 200),
          curve: Curves.easeOut,
        );
      }
    } else if (state1 == 2) {
      if (nameCheck() && addressCheck() && desCheck()) {
        state.currentPageState.value = state1;
        state.mainPage.animateToPage(
          state1,
          duration: Duration(milliseconds: 200),
          curve: Curves.easeOut,
        );
      }
    } else {
      state.currentPageState.value = state1;
      state.mainPage.animateToPage(
        state1,
        duration: Duration(milliseconds: 200),
        curve: Curves.easeOut,
      );
    }
  }

  bool nameCheck() {
    return state.nameA.text.isNotEmpty || state.nameE.text.isNotEmpty;
  }

  bool addressCheck() {
    return state.addressA.text.isNotEmpty || state.addressE.text.isNotEmpty;
  }

  bool desCheck() {
    return state.descriptionE.text.isNotEmpty ||
        state.descriptionA.text.isNotEmpty;
  }

  bool videoCheck() {
    return state.video.text.isNotEmpty;
  }

  bool costCheck() {
    return state.cost.text.isNotEmpty ;
  }

  bool numOfRooms() {
    return state.numOfRooms.text.isNotEmpty ;
  }
  bool numOfBathRooms() {
    return state.numOfBath.text.isNotEmpty ;
  }

  void changeSelectedCostType(String newValue) {
    state.selectedCostType = newValue;
    update(['c']);
  }

  void changeSelectedCity(City newValue) {
    state.selectedCity = newValue;
    update(['ci']);
    getZones(state.selectedCity!.id!.toString());
  }

  void changeSelectedZone(Zone newValue) {
    state.selectedZone = newValue;
    update(['z']);
  }

  void changeSelectedType(TypeBuild newValue) {
    state.selectedBuildType = newValue;
    update(['b']);
  }

  void changeGettingCities() =>
      state.gettingCities.value = !state.gettingCities.value;

  void changeGettingZones() =>
      state.gettingZones.value = !state.gettingZones.value;

  void changeGettingBuilds() =>
      state.gettingBuildTypes.value = !state.gettingBuildTypes.value;

  void changeCreateState() =>
      state.createAdsState.value = !state.createAdsState.value;

  void getCities() async {
    changeGettingCities();
    var result = await state.createAdHttp.getAllCities();
    result.fold(
      (l) {
        state.cities = [];
        update(['ci']);
        // Get.snackbar('Error'.tr, 'please check your internet connection'.tr);
        mySnackBar(title: 'Error'.tr,body: 'please check your internet connection'.tr);
      },
      (r) {
        state.cities = r.cities!;
        print(state.cities.length);

        update(['ci']);
      },
    );
    changeGettingCities();
  }

  void getBuildTypes() async {
    changeGettingBuilds();
    var result = await state.createAdHttp.getAllBuildTypes();
    result.fold(
      (l) {
        state.cities = [];
        update(['b']);
        // Get.snackbar('Error'.tr, 'please check your internet connection'.tr);
        mySnackBar(title: 'Error'.tr,body: 'please check your internet connection'.tr);
      },
      (r) {
        state.typeBuilds = r.typeBuild!;
        print(state.cities.length);

        update(['b']);
      },
    );
    changeGettingBuilds();
  }

  void getZones(String id) async {
    update(['z']);
    changeGettingZones();
    update(['z']);
    var result = await state.createAdHttp.getAllZones(id: id);
    result.fold(
      (l) {
        state.zones = [];
        update(['z']);
        // Get.snackbar('Error'.tr, 'please check your internet connection'.tr);
        mySnackBar(title: 'Error'.tr,body: 'please check your internet connection'.tr);
      },
      (r) {
        state.selectedZone=null;
        if (r.zones!.isNotEmpty) {
          state.zones = r.zones!;
          print(state.zones.length);
          // state.selectedZone = state.zones.first;
          update(['z']);
        } else {
          state.zones = r.zones!;
          print(state.zones.length);
          // state.selectedZone=state.zones.first;
          update(['z']);
        }
      },
    );
    changeGettingZones();
  }

  void getImages() async {
    FilePickerResult? result = await FilePicker.platform
        .pickFiles(allowMultiple: true, type: FileType.image);

    if (result != null) {
      List<File> files = result.paths.map((path) => File(path!)).toList();
      for (int i = 0; i < files.length; i++) {
        if (state.images.length < 5) {
          state.images.add(files[i]);
          state.photos.add(files[i].readAsBytesSync());
        } else {}
      }
      update(['photo']);
    } else {
      // User canceled the picker
    }
  }

  void deleteImage(int index) {
    state.images.removeAt(index);
    state.photos.removeAt(index);
    update(['photo']);
  }

  collectData() {
    if (nameCheck()&&desCheck()&&addressCheck()&&costCheck()&&numOfBathRooms()&&numOfRooms()) {
      if (state.images.isNotEmpty &&
          state.selectedCostType!.isNotEmpty &&
          state.selectedZone != null &&
          state.selectedCity != null &&
          state.selectedBuildType != null) {
        return CreateAdModel(
          nameA:state.langOption.value==0? state.nameE.text:state.nameA.text,
          nameE:state.langOption.value==1?state.nameA.text: state.nameE.text,
          video: state.video.text.isEmpty?'':state.video.text,
          descE:state.langOption.value==1? state.descriptionA.text:state.descriptionE.text,
          descA:state.langOption.value==0?state.descriptionE.text :state.descriptionA.text,
          cost: state.cost.text,
          costType: state.selectedCostType,
          addressE:state.langOption.value==1?state.addressA.text: state.addressE.text,
          addressA: state.langOption.value==0? state.addressE.text:state.addressA.text,
          zoneId: state.selectedZone!.id!.toString(),
          typeBuild: state.selectedBuildType!.id!.toString(),
          numRoom: state.numOfRooms.text,
          numBathroom: state.numOfRooms.text,
          photos: List.generate(
              state.images.length, (index) => state.images[index].path),
        );
      } else {
        return '';
      }
    } else {
      return '';
    }
  }

  void createAD() async {
    print(state.nameE.text);
    print(collectData().toString());
    if (collectData() is CreateAdModel) {
      changeCreateState();
      var result = await state.createAdHttp.createAd(
        createAdModel: collectData(),
        photos: state.photos,
      );
      result.fold(
        (l) {
          print(l);
          if (l == 'User package expired') {
            Get.dialog(PackageExDialog());
          } else if (l == 'please Complate Your Date') {
            Get.dialog(DataDialog());
          } else {
            // Get.snackbar('Error'.tr, l.toString().tr);
            mySnackBar(title: 'Error'.tr,body: l.toString().tr);
          }
        },
        (r) {
          Get.back();
          // Get.snackbar('Done'.tr, 'Ads has been sent'.tr);
          mySnackBar(title: 'Done'.tr,body: 'Ads has been sent'.tr);
        },
      );
      changeCreateState();
    }
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getBuildTypes();
    getCities();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
