/// Generated by Flutter GetX Starter on 2022-10-09 19:24
import 'package:ejarkom/app/Ads/create_ads/modes/photo_selector.dart';
import 'package:ejarkom/app/Ads/create_ads/widgets/build_selector.dart';
import 'package:ejarkom/app/Ads/create_ads/widgets/city_selector.dart';
import 'package:ejarkom/app/Ads/create_ads/widgets/cost_type_selector.dart';
import 'package:ejarkom/app/Ads/create_ads/widgets/my_from_feild.dart';
import 'package:ejarkom/app/Ads/create_ads/widgets/zone_selector.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';

import 'create_ads_logic.dart';
import 'create_ads_state.dart';
import 'modes/data_selector.dart';
import 'modes/info_selector.dart';

class CreateAdsView extends StatefulWidget {
  @override
  _CreateAdsViewState createState() => _CreateAdsViewState();
}

class _CreateAdsViewState extends State<CreateAdsView> {
  final CreateAdsLogic logic = Get.put(CreateAdsLogic());
  final CreateAdsState state = Get.find<CreateAdsLogic>().state;

  @override
  void dispose() {
    Get.delete<CreateAdsLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
        leading: Obx(
          () => state.currentPageState.value == 0
              ? IconButton(
                  onPressed: () {
                    Get.back();
                  },
                  icon: Icon(
                    Icons.arrow_back_ios,
                    color: Get.theme.primaryColor,
                  ),
                )
              : Container(),
        ),
        title: Text(
          'New AD'.tr,
          style: Get.textTheme.bodyText1!.copyWith(
            fontSize: 40.sp,
            color: Get.theme.primaryColor,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Container(
        height: Get.height,
        decoration: const BoxDecoration(
          color: Colors.white,
          image: DecorationImage(
            image: AssetImage('assets/images/newb.png'),
            fit: BoxFit.fitHeight,
          ),
        ),
        child: SizedBox(
          height: Get.height,
          width: Get.width,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 15.w),
            child: SingleChildScrollView(
              child: SizedBox(
                  height: Get.height,
          width: Get.width,
                child: PageView(
                  physics: const NeverScrollableScrollPhysics(),
                  controller: state.mainPage,
                  children: [
                    PhotosSelector(),
                    InfoSelector(),
                    DataSelector(),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  List<double> _getCustomItemsHeights() {
    List<double> _itemsHeights = [];
    for (var i = 0; i < (state.costTypes.length * 2) - 1; i++) {
      if (i.isEven) {
        _itemsHeights.add(40);
      }
      //Dividers indexes will be the odd indexes
      if (i.isOdd) {
        _itemsHeights.add(4);
      }
    }
    return _itemsHeights;
  }
}
