/// Generated by Flutter GetX Starter on 2022-10-18 22:49
import 'package:ejarkom/app/my_checks/models/CheckupsRequestModel.dart';
import 'package:get/get.dart';

import 'my_checks_state.dart';

class MyChecksLogic extends GetxController {
  final state = MyChecksState();

  void changePageState() =>
      state.gettingState.value = !state.gettingState.value;

  void getPage() async {
    changePageState();
    var result = await state.requestsHttp.getChecks();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changePageState();
  }

  void pageDone(CheckupsRequestModel checkupsRequestModel) {
    state.checks = checkupsRequestModel.myData!;
  }

  void pageError(String e) {
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}