import 'package:ejarkom/app/my_checks/models/CheckupsRequestModel.dart';
import 'package:ejarkom/utils/http_manager/create_ad_http.dart';
import 'package:ejarkom/utils/http_manager/requests_http.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-18 22:49
class MyChecksState {
  MyChecksState() {
    requestsHttp = RequestsHttp();
  }
  RxBool gettingState = false.obs;
  late List<Check> checks;
  late RequestsHttp requestsHttp;
}
