/// Generated by Flutter GetX Starter on 2022-10-16 04:31
import 'package:get/get.dart';

import 'cancel_services_dialog_state.dart';

class CancelServicesDialogLogic extends GetxController {
  final state = CancelServicesDialogState();
  void changeCancelState() =>
      state.cancelState.value = !state.cancelState.value;

  void cancelAd({required String id}) async {
    changeCancelState();
    var result = await state.servicesHttp.cancelServices(id: id);
    result.fold(
      (l) {
        Get.snackbar('Error'.tr, l);
      },
      (r) {
        Get.back();
        Get.snackbar('Done'.tr, 'Request has been Canceled'.tr);
      },
    );
    changeCancelState();
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
