import 'package:ejarkom/utils/http_manager/services_htt.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-16 04:31
class CancelServicesDialogState {
  CancelServicesDialogState() {
    servicesHttp=ServicesHttp();
  }
  RxBool cancelState = false.obs;
  late ServicesHttp servicesHttp;
}
