/// Generated by Flutter GetX Starter on 2022-10-16 04:31
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

import 'cancel_services_dialog_logic.dart';
import 'cancel_services_dialog_state.dart';

class CancelServicesDialogView extends StatefulWidget {
  late String id;

  CancelServicesDialogView({required this.id});

  @override
  _CancelServicesDialogViewState createState() =>
      _CancelServicesDialogViewState();
}

class _CancelServicesDialogViewState extends State<CancelServicesDialogView> {
  final CancelServicesDialogLogic logic = Get.put(CancelServicesDialogLogic());
  final CancelServicesDialogState state =
      Get.find<CancelServicesDialogLogic>().state;

  @override
  void dispose() {
    Get.delete<CancelServicesDialogLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      return AlertDialog(
        title: Row(
          children: [
            IconButton(
              onPressed: state.cancelState.value
                  ? null
                  : () {
                      Get.back();
                    },
              icon: const Icon(Icons.close),
            )
          ],
        ),
        content: state.cancelState.value
            ? Column(
                mainAxisSize: MainAxisSize.min,
                children: const [
                  MyIndicator(),
                ],
              )
            : Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    'Are you sure to cancel this Service AD?'.tr,
                    style: Get.textTheme.bodyText1,
                  ),
                  SizedBox(height: 15.h),
                  ElevatedButton(
                    onPressed: () {
                      logic.cancelAd(id: widget.id);
                    },
                    style: ElevatedButton.styleFrom(
                        fixedSize: Size(Get.width / 2.w, 40.h)),
                    child: Text(
                      'Yes'.tr,
                      style: Get.textTheme.bodyText1!.copyWith(
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ],
              ),
      );
    });
  }
}
