const Map<String, String> ar = {
  // "Forget Password?":'نسيب كلمة المرور؟'
  'As A Company?':'كـ شركة؟',
  'Login to your account': 'تسجيل الدخول الى حسابك',
  'E-Mail': 'الحساب الالكترونى',
  'Password': 'كلمة المرور',
  'Forget Password?': 'نسيت كلمة المرور؟',
  'Login': 'تسجيل دخول',
  'If you do not have an account,': 'اذا لا تمتلك حساب',
  'Sign up': 'سجل حساب جديد',
  'Error': 'حطأ',
  'No Internet Connection': 'لا يوجد اتصال بـ الانترنت',
  'Some thing want wrong': 'حدث خطأ ما',
  'please complete your data': 'من فضلك اكمل معلوماتك',
  'Done': 'تم',
  'Password has been changed': 'تم تغير كلمة المرور',
  // 'please complete your data':'please complete your data',
  'Change Password': 'تغير كلمة المرور',
  'New Password': 'كلمة مرور جديد',
  // 'Change Password':'Change Password',
  'Email Verification': 'تأكيد البريد الالكترونى',
  'Enter the code sent to': 'ادخل الرقم المرسل الى ',
  'The code is incorrect': 'الرقم غير صحيح',
  'The user or password is incorrect':
      'ربما البريد الالكترونى غيى صحيح او كلمة المرور',
  //--------------------Login---------------------------//
  'Add Photo': 'اضافة صورة',
  'Full Name': 'الاسم بـ الكامل',
  'Phone': 'رقم الهاتف',
  'JOD':'د.أ',
  // 'Password':'Password',
  're-password': "اعادة كلمة المرور",
  'Weak Password': 'كلمة مرور ضعيفة',
  'please complete the info': 'من فضلك اكمل بياناتك',
  'This email already exists.': 'هذا البريد الالكترونى موجود بالفعل',
  //--------------------Signup---------------------------//
  'Home': 'الصفحة الرئيسية',
  'Services': 'الخدمات',
  'create Service': 'انشاء خدمة',
  'create ADS': 'انشاء اعلان',
  'View all': 'عرض الجميع',

  'Both': 'الاثنين',
  'Name In English': 'الاسم بـ الللغة الانجليزية',
  'Name In Arabic': 'الاسم بـ اللغة العربية',
  'Description In English': 'الوصف بـ اللغة الانجليزية',
  'Description In Arabic': 'الوصف بـ اللغة العربية',
  'WhatsApp': 'الواتساب',
  'Next': 'التالى',
  'one image at least and five at most':
      'صورة واحدة على الاقل و خمس صور على الاكثر',
  'Select City': 'اختر المدينة',
  'Select Zone': 'اختر المحافظة',
  'No Zones on this area yet': 'لا توجد محافظات فى هذه المدينة',
  'Select Service Type': 'اختر نوع الخدمة',
  'Number of Days:': 'عدد الايام:',
  'please check your internet connection':
      'من فضلك تاكد من ااتصالك بـ الانترنت',
  'please select pandle': 'من فضلك اختر الباقة',
  'Please enter WhatsApp': 'من فضلك ادخل الواتساب',
  'Please enter Phone': 'من فضلك ادخل رقم الهاتف',
  'Please enter Description In English':
      'من فضلك ادخل الوصف بـ اللغة الانجليزية',
  'Please enter Description In Arabic': 'من فضلك ادخل الوصف بـ اللغة العربية',
  'Please enter name In Arabic': 'من فضلك ادخل الاسم بـ اللغة العربية',
  'Please enter name In English': 'من فضلك ادخل الاسم بـ اللغة الانجليزية',
  'Please select Type': 'من فضلك اختر النوع',
  'Please select Zone': 'من فضلك اختر المحافظة',
  'Please select City': 'من فضلك اختر المدينة',
  'Please add photos': 'من فضلك قم بـ اضافة صور',
  'Service Ad Has been published': 'اعلان الخدمة تم نشره',
  'Start to publish this service AD?': 'البدء فى نشر اعلان هذه الخدمة؟',
  'Yes': 'نعم',
  'No': 'لا',
  'Back': 'عودة',
  'Create Services ad': 'انشاء اعلان خدمة',
  'No Ads Yet':'No Ads Yet',
  'All Ads':'جميع الاعلانات',
  'Filter':'تصفية',
  'Requests':'الطلبات',
  'Rent':'تقديم طلب',
  'Your request has been send':'لقد تم تقديم طلبك',
  'Your information is not complete yet':'بياناتك غيى مكتملة',
  'complete Info':'اكمل بياناتك',
  'show more':'اظهر المزيد',
  'show less':'اظهر الاقل',
  'Current package:':"عدد الاعلانات:",
  'Home Screen':'الصفة الرئسية',
  'My Informtions':'معلوماتى',
  'Ads':'اعلاناتى',
  'My Services ADs':'اعلانات خدماتى',
  'Packages':'الباقات',
  'My Requests':'الطلبات المقدمة لى',
  'Management Requests':'طلبات الادارة',
  'Update Profile':'تحديث الملف الشخصى',
  'Help':'المساعدة',
  'privacy policy':'سياسة الخصوصية',
  'Log out':'تسجيل الخروج',
  'Address In English':'العنوان بـ اللغة الانجليزية',
  'Please enter Address In English':'من فضلك ادخل العنوان بـ اللغة الانجليزية',
  'Address In Arabic':'العنوان بـ اللغة العربية',
  'Please enter Address In Arabic':'من فضلك ادخل العنوان بـ الللغة العربية',
  'video link on youtube (optional)':'رابط يوتيوب للاعلان(اختيارى)',
  'Cost':'التكلفة',
  'Please enter Cost':'نوع التكلفة',
  'Number Of Rooms':'عدد الغرف',
  'Please enter Number Of Rooms':'من فضلك ادخل عدد الغرف',
  'Number Of Baths':'عدد الحمامات',
  'Please enter Baths':'من فضلك ادخل عدد الحمامات',
  'Select Cost Type':'اختر نوع التكلفة',
  'Monthly':'شهرى',
  'Weekly':'اسبوعى',
  'Annually':'سنوى',
  'Daily':'يومى',
  'Select your building Type':'اختر نوع المبنى',
  'Create AD':'انشاء اعلان',
  'You Ads Package Is Over':'انتهت صلاحية الباقة الخاصة بك',
  'Cancel':'الغاء',
  'Get New Package':'احصل على باقة جديدة',
  'Your data is not complete':'بياناتك غيى مكتملة',
  'complete Data':'اكمل البيانات',
  'Ads has been sent':'الاعلان تم ارساله للمراجعة',
  'New AD':'اعلان جديد',
  'Informations':'معلوماتى',
  'Address':'العنوان',
  'Date Of Birth "9-8-1990"':'تاريخ الميلاد "٩-٨-٢٠٠١"',
  'Your ID(Front)':'هويتك من الامام',
  'Your Id(Back)':"هويتك من الخلف",
  'No Data Yet':'لا توجد معلومات عنك حتى الان',
  'Date Of Birth:':'تاريخ الميلاد:',
  'Address:':'العنوان:',
   'Waiting....':'قيد الانتظار....',
  'Accepted':'مقبولة',
  'Rejected':'مرفوضة',
  'Complete':'انهاء',
  'My ADS':'اعلاناتى',
  'Waitting':"قيد الانتظار",
  'Ready':'جاهزة',
  'Finished':'منتهية',
  'Canceled':'ملغية',
  'No Ads Yet.':'لا توجد اعلانات',
  'Show':'عرض',
  'Are you sure to cancel this AD?':'هل انت متاكد من الغاء هذا الاعلان؟',
  'Are you sure to cancel this Service AD?':'هل انت متاكد من الغاء هذا الاعلان؟',
  'No Services Yet.':'لا توجد خدمات حتى الان',
  'Number of Ads:':'عدد الاعلانات:',
  'No Packages Yet.':'لا توجد باقات الان.',
  'No Requests Yet.':'لا توجد طلبات حتى الان.',
  'Management Request':'طلب ادارة',
  'This Request has been Sent':'تم ارسال الطلب',
  'Name':'الاسم',
  'Data has been updated':'تم تحديث البيانات',
  'Message':'رسالة',
  'Your Request is now':'طلبك الان',
  'Your Ads is now':'اعلانك الان',
  'Your Services ads is now':'اعلان خدمتك الان',
  'Your Managment Request has a response':'طلبك للادارة لديه رد الان',
  'Your data has a response':'بيناناتك لديها رد',
  'Remove My Account':'حذف حسابى',
  'Verification Type':'طريقة التأكيد',
  'Code Verification':'تأكيد الرمز',
  'Complete Signup':'اكمال التسجيل',
  // 'Email Verification':'تأكيد البريد الالكترونى',
  'Phone Verification Type':'طريقة تأكيد رقم الهاتف',
  'Phone Verification':'تأكيد رقم الهاتف',
  'Enter the code sent to your':'ادخل الرمز المرسل الى',
  'Code':'رمز',
  // 'Next':'التالى',
  'Send':'ارسال',
  'resend':'اعادة ارسال',
  'Whatsapp':'واتساب',
  'Sending Code to?':'ارسال الرمز الى',
  'The Code Has Been Send':'تم ارسال الرمز',
  'You can resend now':'تستطيع اعادة الارسال الان',
  'User Not Found':'المستخدم غير موجود',
  'please enter your Phone or E-mail':'من فضلك ادخل الحساب الالكترونى او رقم الهاتف',
  // 'Change Password':'Change Password',
  // 'Password':'Password', 'E-mail or phone':'الحساب الالكترونى او رقم الهاتف',

  // 'Password':'Password',

  'Logout':'تسجيل الخروج',
 
  // 'please complete your data':'please complete your data',

     
  //--------------------Login---------------------------//

  //--------------------Signup---------------------------//


'Are you sure you want buy this package?':'هل انت متاكد من شراء هذه الباقة',
  
  'Buy':'شراء',
  // 'Logout':'تسجيل الخروج',
  'Number of Ads ':'عدد الاعلانات',
  'ADS':'الاعلانات',
  'Furnished':'مفروشة',
  'Options':'مواصفات',
  'Quarterly':'ربع سنوية',
  'English':'اللغة الانجليزية',
  'Arabic':'اللغة العربية',

  'half a year':'نصف سنوية',
  'Change Language':'تغير اللغة',
  'Company Data':'بيانات الشركة',
  'Number Of bathroom':'عدد الحمامات',
  'Video':'فيديو',
  'Amount':'المبلغ',
  'Create Ad':'انشاء اعلان',
  
  'Waiting':'قيد الانتظار',
  'Active':'قيد العمل',
  'Canceld Or Rejected':'ملغية او مرفوضة',
  // 'Finished':'انتهت',
  'Invalid Phone Number':'رقم غير صحيح',
  'My Ads':'اعلاناتى',
  
  // 'Ads':'اعلانات',
  
  // 'No Ads Yet.':'لا توجد اعلانات',
 
  'No requests Yet':'لا توجد طلبات حتى الان',
  'Registration Request':'طلب انضمام',
  'Add Company Logo':'اضافة شعار الشركة',
  'Email':'الحساب الالكترونى',
  // 'Requests':'الطلبات',
 
  // 'Email Verification':'تأكيد البريد الالكترونى',
  
  'you do not have an data yet.':'لم تقم بـ اضافة بيانات بعد.',
  'My Data':'معلوماتى',
  'Add Company Id':'بطاقة الشركة',
  'Add Owner Id':'بطاقة مالك الشركة',
  'Send New Data':'ارسال بيانات جديدة.',

  // 'Change Password':'Change Password',
  // 'Change Password':'Change Password',
  // 'Password':'Password',
  
};
