const Map<String, String> en = {
  'Login to your account': 'Login to your account',
  'E-Mail': 'E-Mail',
  'Password': 'Password',
  'Forget Password?': 'Forget Password?',
  'Login': 'Login',
  'If you do not have an account,': 'If you do not have an account,',
  'Sign up': 'Sign up',
  'Error': 'Error',
  'No Internet Connection': 'No Internet Connection',
  'Some thing want wrong': 'Some thing want wrong',
  'please complete your data': 'please complete your data',
  'Done': 'Done',
  'Password has been changed': 'Password has been changed',
  // 'please complete your data':'please complete your data',
  'Change Password': 'Change Password',
  'New Password': 'New Password',
  // 'Change Password':'Change Password',
  'Email Verification': 'Email Verification',
  'Enter the code sent to': 'Enter the code sent to',
  'The code is incorrect': 'The code is incorrect',
  'The user or password is incorrect': 'The user or password is incorrect',
  //--------------------Login---------------------------//
  'Add Photo': 'Add Photo',
    'Verification Type':'Verification Type',
    // 'No Data Yet':'No Data Yet',
  'Code Verification': 'Code Verification',
  'Full Name': 'Full Name',
  'Phone': 'Phone',
  // 'Password':'Password',
  're-password': "re-password",
  'Weak Password': 'Weak Password',
  'please complete the info': 'please complete the info',
  'This email already exists.': 'This email already exists.',
  // 'Sign up':'Sign up'
  //--------------------signup---------------------------//
  'Home': 'Home',
  'Services': 'Services',
  'create Service': 'create Service',
  'create ADS': 'create ADS',
  'View all': 'View all',
  'Both': 'Both',
  'Name In English': 'Name In English',
  'Name In Arabic': 'Name In Arabic',
  'Description In English': 'Description In English',
  'Description In Arabic': 'Description In Arabic',
  'WhatsApp': 'WhatsApp',
  'Next': 'Next',
  'one image at least and five at most': 'one image at least and five at most',
  'Select City': 'Select City',
  'Select Zone': 'Select Zone',
  'No Zones on this area yet': 'No Zones on this area yet',
  'Select Service Type': 'Select Service Type',
  'Number of Days:': 'Number of Days:',
  'please check your internet connection':
      'please check your internet connection',
  'please select pandle': 'please select pandle',
  'Please enter WhatsApp': 'Please enter WhatsApp',
  'Please enter Phone': 'Please enter Phone',
  'Please enter Description In English': 'Please enter Description In English',
  'Please enter Description In Arabic': 'Please enter Description In Arabic',
  'Please enter name In Arabic': 'Please enter name In Arabic',
  'Please enter name In English': 'Please enter name In English',
  'Please select Type': 'Please select Type',
  'Please select Zone': 'Please select Zone',
  'Please select City': 'Please select City',
  'Please add photos': 'Please add photos',
  'Service Ad Has been published': 'Service Ad Has been published',
  'Start to publish this service AD?': 'Start to publish this service AD?',
  'Yes': 'Yes',
  'No': 'No',
  'Back': 'Back',
  'Create Services ad': 'Create Services ad',
  'No Ads Yet':'No Ads Yet',
  'All Ads':'All Ads',
  'Filter':'Filter',
  'Requests':'Requests',
  'Rent':'Rent',
  'Your request has been send':'Your request has been send',
  'Your information is not complete yet':'Your information is not complete yet',
  'complete Info':'complete Info',
  'show more':'show more',
  'show less':'show less',
  'Numbers of Ads:':'Numbers of Ads:',
  'Home Screen':'Home Screen',
  'My Informtions':'My Informtions',
  'Ads':'Ads',
  'My Services ADs':'My Services ADs',
  'Packages':'Packages',
  'My Requests':'My Requests',
  'Management Requests':'Management Requests',
  'Update Profile':'Update Profile',
  'Help':'Help',
  'privacy policy':'privacy policy',
  'Log out':'Log out',
  'Address In English':'Address In English',
  'Please enter Address In English':'Please enter Address In English',
  'Address In Arabic':'Address In Arabic',
  'Please enter Address In Arabic':'Please enter Address In Arabic',
  'video link on youtube (optional)':'video link on youtube (optional)',
  'Cost':'Cost',
  'Please enter Cost':'Please enter Cost',
  'Number Of Rooms':'Number Of Rooms',
  'Please enter Number Of Rooms':'Please enter Number Of Rooms',
  'Number Of Baths':'Number Of Baths',
  'Please enter Baths':'Please enter Baths',
  'Select Cost Type':'Select Cost Type',
  'Monthly':'Monthly',
  'Weekly':'Weekly',
  'Annually':'Annually',
  'Daily':'Daily',
  'Select your building Type':'Select your building Type',
  'Create AD':'Create AD',
  'You Ads Package Is Over':'You Ads Package Is Over',
  'Cancel':'Cancel',
  'Get New Package':'Get New Package',
  'Your data is not complete':'Your data is not complete',
  'complete Data':'complete Data',
  'Ads has been sent':'Ads has been sent',
  'New AD':'New AD',
  'Informations':'Informations',
  'Address':'Address',
  'Date Of Birth "9-8-1990"':'Date Of Birth "9-8-1990"',
  'Your ID':'Your ID',
  'Your Signature':"Your Signature",
  'No Data Yet':'No Data Yet',
  'Date Of Birth:':'Date Of Birth:',
  'Address:':'Address:',
  'Waiting....':'Waiting....',
  'Accepted':'Accepted',
  'Rejected':'Rejected',
  'Complete':'Complete',
  'JOD':'JOD',
  'Complete Signup':'Complete Signup',
  // 'Email Verification':'تأكيد البريد الالكترونى',
  'Phone Verification Type':'Phone Verification Type',
  'Phone Verification':'Phone Verification',
  'Enter the code sent to your': 'Enter the code sent to your',
  'Code':'Code',
  'please enter your Phone or E-mail':'please enter your Phone or E-mail',
  
  // 'Done':'Done',
  // 'Phone':'Phone',
};
