import 'dart:io';
import 'dart:typed_data';

import 'package:ejarkom/utils/http_manager/rent_http.dart';
import 'package:flutter/cupertino.dart';

/// Generated by Flutter GetX Starter on 2022-10-14 00:05
class CompleteDataState {
  CompleteDataState() {
    address = TextEditingController();
    dob = TextEditingController();
    rentHttp = RentHttp();
  }
  File? image;
  Uint8List? photo;
  File? signatureImage;
  Uint8List? signaturePhoto;
  late TextEditingController address;
  late TextEditingController dob;
  late RentHttp rentHttp;
}
