/// Generated by Flutter GetX Starter on 2022-10-13 00:34
import 'package:get/get.dart';

import 'cancel_dialog_state.dart';

class CancelDialogLogic extends GetxController {
  final state = CancelDialogState();

  void changeCancelState() =>
      state.cancelState.value = !state.cancelState.value;

  void cancelAd({required String id}) async {
    changeCancelState();
    var result = await state.createAdHttp.cancelAD(id: id);
    result.fold(
      (l) {
        Get.snackbar('Error'.tr, l);
      },
      (r) {
        Get.back();
        Get.snackbar('Done'.tr, 'AD has been Canceled'.tr);
      },
    );
    changeCancelState();
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
