import 'package:ejarkom/utils/http_manager/create_ad_http.dart';
import 'package:get/get_rx/src/rx_types/rx_types.dart';

/// Generated by Flutter GetX Starter on 2022-10-13 00:34
class CancelDialogState {
  CancelDialogState() {
    createAdHttp = CreateAdHttp();
  }
  RxBool cancelState = false.obs;
  late CreateAdHttp createAdHttp;
}
