/// Generated by Flutter GetX Starter on 2022-10-13 00:34
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

import 'cancel_dialog_logic.dart';
import 'cancel_dialog_state.dart';

class CancelDialogView extends StatelessWidget {
  final CancelDialogLogic logic = Get.put(CancelDialogLogic());
  final CancelDialogState state = Get.find<CancelDialogLogic>().state;

  String? id;
  String? name;

  CancelDialogView({required this.id, required this.name});

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      return AlertDialog(
        title: Row(
          children: [
            IconButton(
              onPressed: state.cancelState.value
                  ? null
                  : () {
                      Get.back();
                    },
              icon: const Icon(Icons.close),
            )
          ],
        ),
        content: state.cancelState.value
            ? Column(
                mainAxisSize: MainAxisSize.min,
                children: const [
                  MyIndicator(),
                ],
              )
            : Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    'Are you sure to cancel this AD?'.tr,
                    style: Get.textTheme.bodyText1,
                  ),
                  SizedBox(height: 15.h),
                  ElevatedButton(
                    onPressed: () {
                      logic.cancelAd(id: id!);
                    },
                    style: ElevatedButton.styleFrom(
                        fixedSize: Size(Get.width / 2.w, 40.h)),
                    child: Text(
                      'Yes'.tr,
                      style: Get.textTheme.bodyText1!.copyWith(
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ],
              ),
      );
    });
  }
}
