/// Generated by Flutter GetX Starter on 2022-10-16 00:25
import 'package:ejarkom/app/services/view_service/widgets/services_card.dart';
import 'package:ejarkom/utils/apis.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:get/get.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';

import 'view_service_logic.dart';
import 'view_service_state.dart';

class ViewServiceView extends StatefulWidget {
  @override
  _ViewServiceViewState createState() => _ViewServiceViewState();
}

class _ViewServiceViewState extends State<ViewServiceView> {
  final ViewServiceLogic logic = Get.find<ViewServiceLogic>();
  final ViewServiceState state = Get.find<ViewServiceLogic>().state;

  @override
  void dispose() {
    Get.delete<ViewServiceLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Obx(
      () {
        return state.getState.value
            ? const Scaffold(
                body: MyIndicator(),
              )
            : Scaffold(
                appBar: AppBar(
                  centerTitle: true,
                  backgroundColor: Colors.white,
                  elevation: 0,
                  title: Text(
                    'Services'.tr,
                    style: Get.textTheme.bodyText1!.copyWith(
                      color: Get.theme.primaryColor,
                    ),
                  ),
                  leading: IconButton(
                    onPressed: () {
                      Get.back();
                    },
                    icon: Icon(
                      Icons.arrow_back_ios,
                      color: Get.theme.primaryColor,
                    ),
                  ),
                ),
                body: Container(
                  decoration: const BoxDecoration(
                    color: Colors.white,
                    image: DecorationImage(
                      image: AssetImage('assets/images/newb.png'),
                      fit: BoxFit.fitHeight,
                    ),
                  ),
                  height: Get.height,
                  child: state.sers.isEmpty
                      ? Center(
                          child: Text(
                            'No Ads Yet'.tr,
                            style: Get.textTheme.bodyText1,
                          ),
                        )
                      : Padding(
                          padding: EdgeInsets.symmetric(
                            horizontal: 10.w,
                            vertical: 10.h,
                          ),
                          child: ListView.builder(
                            itemCount: state.sers.length,
                            itemBuilder: (context, index) {
                              return Padding(
                                padding: EdgeInsets.symmetric(vertical: 10.h),
                                child: ServiceCard(ads: state.sers[index]),
                              );
                            },
                          ),
                        ),
                ),
              );
      },
    );
  }
}
