/// Generated by Flutter GetX Starter on 2022-10-16 00:25
import 'package:ejarkom/utils/apis.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:get/get.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';

import 'view_service_logic.dart';
import 'view_service_state.dart';

class ViewServiceView extends StatefulWidget {
  @override
  _ViewServiceViewState createState() => _ViewServiceViewState();
}

class _ViewServiceViewState extends State<ViewServiceView> {
  final ViewServiceLogic logic = Get.find<ViewServiceLogic>();
  final ViewServiceState state = Get.find<ViewServiceLogic>().state;

  @override
  void dispose() {
    Get.delete<ViewServiceLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Obx(
      () {
        return state.getState.value
            ? const Scaffold(
                body: MyIndicator(),
              )
            : Scaffold(
                appBar: AppBar(
                  centerTitle: true,
                  backgroundColor: Colors.transparent,
                  elevation: 0,
                  title: Text(
                    state.serviceAds.id == -1 ? '' : state.serviceAds.nameE!,
                    style: Get.textTheme.bodyText1!.copyWith(
                      color: Get.theme.primaryColor,
                    ),
                  ),
                  leading: IconButton(
                    onPressed: () {
                      Get.back();
                    },
                    icon: Icon(
                      Icons.arrow_back_ios,
                      color: Get.theme.primaryColor,
                    ),
                  ),
                ),
                body: state.serviceAds.id == -1
                    ? Text(
                        'data',
                        style: Get.textTheme.bodyText1,
                      )
                    : Padding(
                        padding: EdgeInsets.symmetric(
                          horizontal: 10.w,
                          vertical: 10.h,
                        ),
                        child: Column(
                          mainAxisSize: MainAxisSize.max,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Column(
                              children: [
                                SizedBox(
                                  height: 260.h,
                                  width: Get.width,
                                  child: PageView.builder(
                                    itemBuilder: (context, index) {
                                      return Stack(
                                        alignment: Alignment.bottomCenter,
                                        children: [
                                          Image.network(
                                              // '$photoAPI${state.serviceAds.getPhoto()[index]}',
                                              'https://www.ubm-development.com/magazin/wp-content/uploads/2020/03/kl-main-building-d-Kopie.jpg'),
                                        ],
                                      );
                                    },
                                    itemCount:
                                        state.serviceAds.getPhoto().length,
                                    onPageChanged: (value) {
                                      state.currentIndex.value = value;
                                    },
                                    controller: state.pageController,
                                  ),
                                ),
                                SizedBox(height: 10.h),
                                Obx(
                                  () => AnimatedSmoothIndicator(
                                    activeIndex: state.currentIndex.value,
                                    count: state.serviceAds.getPhoto().length,
                                    effect: JumpingDotEffect(
                                      activeDotColor: Get.theme.primaryColor,
                                      dotHeight: 10.h,
                                      dotWidth: 10.h,
                                    ),
                                  ),
                                )
                              ],
                            ),
                            SizedBox(height: 30.h),
                            Row(
                              children: [
                                Icon(Icons.description_outlined),
                                SizedBox(width: 10.h),
                                Text(
                                  '${state.serviceAds.textE!}',
                                  style: Get.theme.textTheme.bodyText1,
                                  textAlign: TextAlign.start,
                                  softWrap: true,
                                ),
                              ],
                            ),
                            SizedBox(height: 30.h),
                            Row(
                              children: [
                                Icon(Icons.location_city),
                                SizedBox(width: 10.h),
                                Text(
                                  '${state.serviceAds.cityE},${state.serviceAds.zonesE}',
                                  style: Get.theme.textTheme.bodyText1,
                                )
                              ],
                            ),
                            SizedBox(height: 30.h),
                            Row(
                              children: [
                                Icon(Icons.phone),
                                SizedBox(width: 10.h),
                                Text(
                                  state.serviceAds.phone!.toString(),
                                  style:
                                      Get.theme.textTheme.bodyText1!.copyWith(
                                    color: Colors.black54,
                                  ),
                                )
                              ],
                            ),
                            SizedBox(height: 30.h),
                            Row(
                              children: [
                                Icon(FontAwesomeIcons.whatsapp),
                                SizedBox(width: 10.h),
                                Text(
                                  state.serviceAds.whats!.toString(),
                                  style:
                                      Get.theme.textTheme.bodyText1!.copyWith(
                                    color: Colors.black54,
                                  ),
                                )
                              ],
                            ),
                          ],
                        ),
                      ),
              );
      },
    );
  }
}
