/// Generated by Flutter GetX Starter on 2022-10-16 00:25
import 'package:ejarkom/app/services/models/ServiceViewModel.dart';
import 'package:get/get.dart';

import 'view_service_state.dart';

class ViewServiceLogic extends GetxController {
  final state = ViewServiceState();

  late String id;

  ViewServiceLogic({required this.id});

  void changeGetState() => state.getState.value = !state.getState.value;

  void getServcies() async {
    changeGetState();
    var result = await state.servicesHttp.getService(id: id);
    result.fold(
      (l) {
        state.serviceAds = ServiceAds(id: -1);
        print(l);
        changeGetState();
      },
      (r) {
        state.serviceAds = r.data!;
        print(state.serviceAds.phone);

        changeGetState();
      },
    );
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getServcies();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
