/// Generated by Flutter GetX Starter on 2022-10-16 00:25
import 'dart:io';

import 'package:ejarkom/app/services/models/ServiceViewModel.dart';
import 'package:get/get.dart';
import 'package:url_launcher/url_launcher.dart';

import 'view_service_state.dart';

class ViewServiceLogic extends GetxController {
  final state = ViewServiceState();

  late String id;

  ViewServiceLogic({required this.id});

  void changeGetState() => state.getState.value = !state.getState.value;

  void getServcies() async {
    changeGetState();
    var result = await state.servicesHttp.getService(id: id);
    result.fold(
      (l) {
        // state.serviceAds = ServiceAds(id: -1);
        state.sers = [];
        print(l);
        changeGetState();
      },
      (r) {
        state.sers = r.adsServes!;

        changeGetState();
      },
    );
  }

  void launchWhatsApp({
    required String phone,
    required String message,
  }) async {
    Uri url() {
      if (Platform.isAndroid) {
        return Uri.parse("https://wa.me/$phone/?text=${Uri.parse(message)}");
      } else {
        return Uri.parse(
            "whatsapp://send?   phone=$phone&text=${Uri.parse(message)}");
      }
    }

    if (await canLaunchUrl(url())) {
      await launchUrl(url());
    } else {
      throw 'Could not launch ${url()}';
    }
  }

  Future<void> launchPhoneDialer(String contactNumber) async {
    final Uri _phoneUri = Uri(scheme: "tel", path: contactNumber);
    try {
      if (await canLaunch(_phoneUri.toString()))
        await launch(_phoneUri.toString());
    } catch (error) {
      throw ("Cannot dial");
    }
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getServcies();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
