/// Generated by Flutter GetX Starter on 2022-10-14 22:28
import 'package:ejarkom/app/requests/models/AllRequestsModel.dart';
import 'package:ejarkom/app/requests/models/requests/requests.dart';
import 'package:ejarkom/utils/apis.dart';
import 'package:get/get.dart';

import 'done_requests_state.dart';

class DoneRequestsLogic extends GetxController {
  final state = DoneRequestsState();
  void changePageState() =>
      state.gettingState.value = !state.gettingState.value;

  void getPage() async {
    changePageState();
    var result = await state.requestsHttp.getWaitingAds(api: myOrdersDoneAPI);
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changePageState();
  }

  void pageDone(Requests adsRequest) {
    state.ads = adsRequest.ads!;
  }

  void pageError(String e) {
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
