import 'package:ejarkom/utils/http_manager/requests_http.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-14 23:34
class CancelRequestDialogState {
  CancelRequestDialogState() {
    requestsHttp = RequestsHttp();
  }
  RxBool cancelState = false.obs;
  late RequestsHttp requestsHttp;
}
