/// Generated by Flutter GetX Starter on 2022-10-14 23:34
import 'package:ejarkom/utils/method.dart';
import 'package:get/get.dart';

import 'cancel_request_dialog_state.dart';

class CancelRequestDialogLogic extends GetxController {
  final state = CancelRequestDialogState();

  void changeCancelState() =>
      state.cancelState.value = !state.cancelState.value;

  void cancelAd({required String id}) async {
    changeCancelState();
    var result = await state.requestsHttp.cancelRequest(id: id);
    // result.fold(
    //   (l) {
    //     Get.snackbar('Error'.tr, l);
    //   },
    //   (r) {
    //     Get.back();
    //     Get.snackbar('Done'.tr, 'Request has been Canceled'.tr);
    //   },
    // );
    result.fold(
      (l) {
        // Get.snackbar('Error'.tr, l);
        mySnackBar(title: 'Error'.tr, body: l);
      },
      (r) {
        Get.back();
        // Get.snackbar('Done'.tr, 'Request has been Canceled'.tr);
        mySnackBar(title: 'Done'.tr, body: 'Request has been Canceled'.tr);
      },
    );
    changeCancelState();
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
