/// Generated by Flutter GetX Starter on 2022-10-11 23:49
import 'package:ejarkom/packs/models/AllPacksModel.dart';
import 'package:get/get.dart';

import 'all_packs_state.dart';

class AllPacksLogic extends GetxController {
  final state = AllPacksState();

  void changePageState() => state.pageIsHere.value = !state.pageIsHere.value;

  void changeAddState() => state.addPackState.value = !state.addPackState.value;

  void addPack({required String id}) async {
    changeAddState();
    var result = await state.packsHttp.addPacks(id: id);
    result.fold(
      (l) {
        Get.snackbar('Error'.tr, '$l');
      },
      (r) {
        Get.back();
        Get.snackbar('Done'.tr, 'you have subscribed to this package'.tr);
      },
    );
    changeAddState();
  }

  void getPage() async {
    changePageState();
    var result = await state.packsHttp.getAllPandles();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changePageState();
  }

  void pageDone(AllPacksModel allPacksModel) {
    state.pandles = allPacksModel.pandleAds!;
  }

  void pageError(String e) {
    state.pandles = [];
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
