/// Generated by Flutter GetX Starter on 2022-10-11 23:49
import 'package:ejarkom/packs/widgets/pack_card.dart';
import 'package:ejarkom/utils/widgets/leading_button.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

import 'all_packs_logic.dart';
import 'all_packs_state.dart';

class AllPacksView extends StatefulWidget {
  @override
  _AllPacksViewState createState() => _AllPacksViewState();
}

class _AllPacksViewState extends State<AllPacksView> {
  final AllPacksLogic logic = Get.put(AllPacksLogic());
  final AllPacksState state = Get.find<AllPacksLogic>().state;

  @override
  void dispose() {
    Get.delete<AllPacksLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: LeadingButton(),
        title: Text(
          'Packages'.tr,
          style: Get.textTheme.bodyText1!.copyWith(
            fontSize: 40.sp,
            color: Get.theme.primaryColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
      ),
      body: Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          image: DecorationImage(
            image: AssetImage('assets/images/newb.png'),
            fit: BoxFit.fitHeight,
          ),
        ),
        height: Get.height,
        child: LayoutBuilder(
          builder: (context, cons) {
            return Padding(
              padding: EdgeInsets.symmetric(horizontal: 20.w),
              child: Column(
                children: [
                  SizedBox(
                    height: cons.maxHeight,
                    child: Obx(
                      () => state.pageIsHere.value
                          ? MyIndicator()
                          : state.pandles.isEmpty
                              ? Center(
                                  child: Text(
                                    'No Packages Yet.'.tr,
                                    style: Get.textTheme.bodyText1,
                                  ),
                                )
                              : ListView.builder(
                                  itemCount: state.pandles.length,
                                  itemBuilder:
                                      (BuildContext context, int index) {
                                    return Padding(
                                      padding:
                                          EdgeInsets.symmetric(vertical: 10.h),
                                      child: PackWidget(
                                        photo: 'assets/images/pack.png',
                                        package: state.pandles[index],
                                      ),
                                    );
                                  },
                                ),
                    ),
                  )
                ],
              ),
            );
          },
        ),
      ),
      // body: Padding(
      //   padding:  EdgeInsets.symmetric(horizontal: 20.w,vertical: 20.h),
      //   child: Obx(
      //     () => state.pageIsHere.value
      //         ? MyIndicator()
      //         : ListView.builder(
      //             itemCount: state.pandles.length,
      //             itemBuilder: (BuildContext context, int index) {
      //               return Padding(
      //                 padding:  EdgeInsets.symmetric(vertical: 10.h),
      //                 child: PackWidget(
      //                   photo: 'assets/images/pack.png',
      //                   package: state.pandles[index],
      //                 ),
      //               );
      //             },
      //           ),
      //   ),
      // ),
    );
  }
}
