/// Generated by Flutter GetX Starter on 2022-10-19 02:13
import 'package:ejarkom/utils/widgets/leading_button.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:get/get.dart';

import 'profile_logic.dart';
import 'profile_state.dart';

class ProfileView extends StatefulWidget {
  @override
  _ProfileViewState createState() => _ProfileViewState();
}

class _ProfileViewState extends State<ProfileView> {
  final ProfileLogic logic = Get.put(ProfileLogic());
  final ProfileState state = Get.find<ProfileLogic>().state;

  @override
  void dispose() {
    Get.delete<ProfileLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: LeadingButton(),
        title: Text(
          'Profile'.tr,
          style: Get.textTheme.bodyText1!.copyWith(
            fontSize: 20.sp,
            color: Get.theme.primaryColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: true,
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.change_circle_outlined),
        backgroundColor: Get.theme.primaryColor,
      ),
      body: Obx(
        () => state.gettingState.value
            ? MyIndicator()
            : Padding(
                padding: EdgeInsets.symmetric(horizontal: 60.w),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Row(
                      // mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        Icon(
                          Icons.email_outlined,
                          size: 30.sp,
                        ),
                        Spacer(),
                        Text(
                          state.userData.email!,
                          style: Get.textTheme.bodyText1,
                        )
                      ],
                    ),
                    Divider(color: Colors.black38),
                    Row(
                      // mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Icon(
                          Icons.person,
                          size: 30.sp,
                        ),
                        Spacer(),
                        Text(
                          state.userData.name!,
                          style: Get.textTheme.bodyText1,
                        )
                      ],
                    ),
                    Divider(color: Colors.black38),
                    Row(
                      // mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Icon(
                          Icons.phone,
                          size: 30.sp,
                        ),
                        Spacer(),
                        Text(
                          state.userData.phone!,
                          style: Get.textTheme.bodyText1,
                        )
                      ],
                    ),
                    Divider(color: Colors.black38),
                    Row(
                      // mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Icon(
                          Icons.ads_click,
                          size: 30.sp,
                        ),
                        Spacer(),
                        Text(
                          state.userData.numAds!.toString(),
                          style: Get.textTheme.bodyText1,
                        )
                      ],
                    ),
                  ],
                ),
              ),
      ),
    );
  }
}
