/// Generated by Flutter GetX Starter on 2022-10-19 02:13
import 'package:ejarkom/app/profile/models/ProfileModel.dart';
import 'package:get/get.dart';

import 'profile_state.dart';

class ProfileLogic extends GetxController {
  final state = ProfileState();

  void changePageState() =>
      state.gettingState.value = !state.gettingState.value;

  void getPage() async {
    changePageState();
    var result = await state.profileHttp.getProfile();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changePageState();
  }

  void pageDone(ProfileModel profileModel) {
    state.userData = profileModel.dataUser!;
  }

  void pageError(String e) {
    Get.snackbar('Error'.tr, e.toString());
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}