/// Generated by Flutter GetX Starter on 2022-10-19 02:13
import 'package:ejarkom/app/home/logic.dart';
import 'package:ejarkom/app/profile/models/ProfileModel.dart';
import 'package:ejarkom/utils/method.dart';
import 'package:get/get.dart';

import 'profile_state.dart';

class ProfileLogic extends GetxController {
  final state = ProfileState();

  void changePageState() =>
      state.gettingState.value = !state.gettingState.value;
  void changeUpdateState() =>
      state.updateState.value = !state.updateState.value;

  void getPage() async {
    changePageState();
    var result = await state.profileHttp.getProfile();
    result.fold((l) => pageError(l), (r) => pageDone(r));
    changePageState();
  }

  void pageDone(ProfileModel profileModel) {
    state.userData = profileModel.dataUser!;
    state.name.text = state.userData.name!;
    state.phone.text = state.userData.phone!;
  }

  void pageError(String e) {
    // Get.snackbar('Error'.tr, e.toString());
    mySnackBar(title: 'Error'.tr, body: e.toString());
  }

  void updatePro() async {
    changeUpdateState();
    var result = await state.profileHttp.updateProfile(
      name: state.name.text == state.userData.name ? '' : state.name.text,
      phone: state.phone.text == state.userData.phone ? '' : state.phone.text,
      password: state.password.text,
    );
    result.fold(
      (l) {
        // Get.snackbar('Error'.tr, l);
        mySnackBar(title: 'Error'.tr, body: l.toString());
      },
      (r) {
        // Get.snackbar('Done'.tr, 'Data has been updated'.tr);
        mySnackBar(title: 'Done'.tr, body: 'Data has been updated'.tr.toString());
        state.isChanged.value = false;
        HomeLogic homeLogic = Get.find();
        getPage();
        homeLogic.getPage();
      },
    );
    changeUpdateState();
  }

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    getPage();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
