import 'package:ejarkom/app/profile/models/ProfileModel.dart';
import 'package:ejarkom/utils/http_manager/profile_http.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-19 02:13
class ProfileState {
  ProfileState() {
    profileHttp = ProfileHttp();
    userData =DataUser();
  }
  RxBool gettingState = false.obs;
  late ProfileHttp profileHttp;
  late DataUser userData;

}
