import 'package:ejarkom/app/profile/models/ProfileModel.dart';
import 'package:ejarkom/utils/http_manager/profile_http.dart';
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-19 02:13
class ProfileState {
  ProfileState() {
    profileHttp = ProfileHttp();
    userData = DataUser();
    name = TextEditingController();
    phone = TextEditingController();
    password = TextEditingController();
  }
  RxBool gettingState = false.obs;
  RxBool updateState = false.obs;
  RxBool isChanged = false.obs;
  late ProfileHttp profileHttp;
  late DataUser userData;
  late TextEditingController name;
  late TextEditingController phone;
  late TextEditingController password;
}
