/// Generated by Flutter GetX Starter on 2022-10-08 18:12
import 'package:ejarkom/app/main/widgets/build_card.dart';
import 'package:ejarkom/app/main/widgets/main_cate.dart';
import 'package:ejarkom/app/main/widgets/search_bar.dart';
import 'package:ejarkom/app/view_all/widgets/build_card_v.dart';
import 'package:ejarkom/app/view_all/widgets/city_selector.dart';
import 'package:ejarkom/app/view_all/widgets/normal_mode.dart';
import 'package:ejarkom/app/view_all/widgets/search_con.dart';
import 'package:ejarkom/app/view_all/widgets/search_mode.dart';
import 'package:ejarkom/app/view_all/widgets/zone_selector.dart';
import 'package:ejarkom/utils/widgets/leading_button.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:get/get.dart';

import 'view_all_logic.dart';
import 'view_all_state.dart';

class ViewAllView extends StatefulWidget {
  @override
  State<ViewAllView> createState() => _ViewAllViewState();
}

class _ViewAllViewState extends State<ViewAllView> {
  final ViewAllLogic logic = Get.find<ViewAllLogic>();

  final ViewAllState state = Get
      .find<ViewAllLogic>()
      .state;

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      return Scaffold(
        appBar: AppBar(
          leading: IconButton(
            onPressed: () {
              Get.back();
              Get.delete<ViewAllLogic>();
            },
            icon: Icon(
              Icons.arrow_back_ios,
              color: Get.theme.primaryColor,
            ),
          ),
          title: Text(
            'All Ads'.tr,
            style: Get.textTheme.bodyText1!.copyWith(
              fontSize: 20.sp,
              color: Get.theme.primaryColor,
              fontWeight: FontWeight.bold,
            ),
          ),
          centerTitle: true,
          backgroundColor: Colors.transparent,
          elevation: 0,
          actions: [
            IconButton(
              onPressed: () {
                // Get.bottomSheet(
                //   // Container(
                //   //   height: 250.h,
                //   //   width: Get.width,
                //   //   decoration: BoxDecoration(
                //   //     color: Colors.white,
                //   //     borderRadius: BorderRadius.only(
                //   //       topLeft: Radius.circular(10.sp),
                //   //       topRight: Radius.circular(10.sp),
                //   //     ),
                //   //   ),
                //   //   child: Padding(
                //   //     padding: EdgeInsets.symmetric(horizontal: 20.w),
                //   //     child: Column(
                //   //       crossAxisAlignment: CrossAxisAlignment.start,
                //   //       children: [
                //   //         IconButton(
                //   //           onPressed: () {
                //   //             logic.state.selectedZone = null;
                //   //             logic.state.selectedCity = null;
                //   //             Get.back();
                //   //           },
                //   //           icon: Icon(Icons.close),
                //   //         ),
                //   //         Column(
                //   //           children: [
                //   //             CitySelectorS(),
                //   //             SizedBox(height: 10.h),
                //   //             GetBuilder<ViewAllLogic>(
                //   //               id: 'z',
                //   //
                //   //               builder: (logic) {
                //   //                 return logic.state.selectedCity != null
                //   //                     ? Obx(() => logic.state.gettingZones.value
                //   //                     ? const MyIndicator()
                //   //                     : ZoneSelectorS())
                //   //                     : Container();
                //   //               },
                //   //             ),
                //   //           ],
                //   //         ),
                //   //         SizedBox(height: 30.h),
                //   //         Center(
                //   //           child: GetBuilder<ViewAllLogic>(
                //   //             id: 'z',
                //   //             builder: (logic) {
                //   //               return ElevatedButton(
                //   //                 onPressed: logic.state.selectedZone == null ? null : () {
                //   //                   logic.changeSearchMode(true);
                //   //                   Get.back();
                //   //                 },
                //   //                 child: Text(
                //   //                   'Filter'.tr,
                //   //                   style: Get.theme.textTheme.bodyText1!.copyWith(
                //   //                     color: Colors.white,
                //   //                   ),
                //   //                 ),
                //   //               );
                //   //             },
                //   //           ),
                //   //         )
                //   //       ],
                //   //     ),
                //   //   ),
                //   // ),
                //   SearchCont(),
                //   elevation: 10,
                //   isDismissible: false,
                //   barrierColor: Colors.black26,
                // );
                Get.dialog(
                  SearchCont()
                );
                // logic.changeSearchMode();
              },
              icon: Icon(
                Icons.filter_list,
                color: Get.theme.primaryColor,
              ),
            )
          ],
        ),
        body: state.getState.value
            ? MyIndicator()
            : Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: EdgeInsets.only(top: 10.h),
              child: SizedBox(
                height: Get.height * 0.9.h,
                child: Obx(() {
                  return state.searchMode.value?SearchMode(): NormalMode();
                }),
              ),
            ),
          ],
        ),
      );
    });
  }
}
