import 'package:ejarkom/app/Ads/models/GetCityModel.dart';
import 'package:ejarkom/app/Ads/models/Zone.dart';
import 'package:ejarkom/app/main/models/PageOneModel.dart';
import 'package:ejarkom/app/view_all/models/AllBuildingsModel.dart';
import 'package:ejarkom/utils/http_manager/create_ad_http.dart';
import 'package:ejarkom/utils/http_manager/main_screen_http.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-08 18:12
class ViewAllState {
  ViewAllState() {
    // allBuildingsModel=AllBuildingsModel();
    mainScreenHTTP = MainScreenHTTP();
    createAdHttp=CreateAdHttp();
    zones=[];
    cities=[];
  }
  RxBool getState = false.obs;
  RxBool searchMode = false.obs;
  AllBuildingsModel? allBuildingsModel;
  List<BuildAds>searchedList=[];
  late MainScreenHTTP mainScreenHTTP;
  late List<City> cities;
  late List<Zone> zones;
  RxBool gettingCities = false.obs;
  RxBool gettingZones = false.obs;
  City? selectedCity;
  Zone? selectedZone;
  late CreateAdHttp createAdHttp;
}
