import 'package:ejarkom/app/BuildsRequest/models/ManagementsRequestsAll.dart';
import 'package:ejarkom/utils/http_manager/create_ad_http.dart';
import 'package:get/get.dart';

/// Generated by Flutter GetX Starter on 2022-10-18 23:47
class AllBuildsRequestsState {
  AllBuildsRequestsState() {
    createAdHttp = CreateAdHttp();
    ads = [];
  }
  RxBool gettingState = false.obs;
  late CreateAdHttp createAdHttp;
  late List<ManagementRequest> ads;
}
