/// Generated by Flutter GetX Starter on 2022-10-18 23:47
import 'package:ejarkom/app/BuildsRequest/add_build_manage/add_build_manage_view.dart';
import 'package:ejarkom/utils/apis.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

import '../../../utils/widgets/leading_button.dart';
import 'all_builds_requests_logic.dart';
import 'all_builds_requests_state.dart';

class AllBuildsRequestsView extends StatefulWidget {
  @override
  _AllBuildsRequestsViewState createState() => _AllBuildsRequestsViewState();
}

class _AllBuildsRequestsViewState extends State<AllBuildsRequestsView> {
  final AllBuildsRequestsLogic logic = Get.put(AllBuildsRequestsLogic());
  final AllBuildsRequestsState state = Get.find<AllBuildsRequestsLogic>().state;

  @override
  void dispose() {
    Get.delete<AllBuildsRequestsLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: LeadingButton(),
        title: Text(
          'Management Requests'.tr,
          style: Get.textTheme.bodyText1!.copyWith(
            fontSize: 40.sp,
            color: Get.theme.primaryColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Get.to(() => AddBuildManageView());
        },
        child: Icon(Icons.add),
        backgroundColor: Colors.amber,
      ),
      body: Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          image: DecorationImage(
            image: AssetImage('assets/images/newb.png'),
            fit: BoxFit.fitHeight,
          ),
        ),
        height: Get.height,
        child: Obx(
          () => Center(
            child: state.gettingState.value
                ? MyIndicator()
                : GetBuilder<AllBuildsRequestsLogic>(builder: (logic) {
                    return state.ads.isEmpty
                        ? Text(
                            'No Requests Yet.'.tr,
                            style: Get.theme.textTheme.bodyText1,
                          )
                        : Padding(
                            padding: EdgeInsets.symmetric(horizontal: 15.w),
                            child: ListView.separated(
                              itemCount: state.ads.length,
                              itemBuilder: (context, index) {
                                return Card(
                                  child: Column(
                                    children: [
                                      Container(
                                        width: Get.width,
                                        height: 400.h,
                                        decoration: BoxDecoration(
                                          borderRadius: BorderRadius.only(
                                            topLeft: Radius.circular(10.sp),
                                            topRight: Radius.circular(10.sp),
                                          ),
                                          image: DecorationImage(
                                            image: NetworkImage(
                                                '$photoAPI${state.ads[index].getPhoto()!}'),
                                            // image: NetworkImage(
                                            //     'https://images.pexels.com/photos/1662159/pexels-photo-1662159.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'),
                                            fit: BoxFit.cover,
                                          ),
                                        ),
                                      ),
                                      Padding(
                                        padding: EdgeInsets.symmetric(
                                          horizontal: 15.w,
                                          vertical: 10.h,
                                        ),
                                        child: Column(
                                          mainAxisAlignment:
                                              MainAxisAlignment.spaceEvenly,
                                          mainAxisSize: MainAxisSize.min,
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Row(
                                              mainAxisAlignment:
                                                  MainAxisAlignment
                                                      .spaceBetween,
                                              children: [
                                                // Row(
                                                //   children: [
                                                //     Icon(
                                                //       Icons.meeting_room_outlined,
                                                //       color: Get.theme.primaryColor,
                                                //     ),
                                                //     SizedBox(width: 6.w),
                                                //     Text(
                                                //       state.ads[index].numRoom!
                                                //           .toString(),
                                                //       style: Get.textTheme.bodyText1!
                                                //           .copyWith(
                                                //         color: Get.theme.primaryColor,
                                                //         fontWeight: FontWeight.bold,
                                                //         fontSize: 20.sp,
                                                //       ),
                                                //     ),
                                                //   ],
                                                // ),
                                                // Row(
                                                //   children: [
                                                //     Icon(
                                                //       Icons.bathroom_outlined,
                                                //       color: Get.theme.primaryColor,
                                                //     ),
                                                //     SizedBox(width: 6.w),
                                                //     Text(
                                                //       state.ads[index].numBathroom!
                                                //           .toString(),
                                                //       style: Get.textTheme.bodyText1!
                                                //           .copyWith(
                                                //         color: Get.theme.primaryColor,
                                                //         fontWeight: FontWeight.bold,
                                                //         fontSize: 20.sp,
                                                //       ),
                                                //     ),
                                                //   ],
                                                // ),
                                              ],
                                            ),
                                            SizedBox(height: 3.h),
                                            Row(
                                              children: [
                                                Text(
                                                  state.ads[index].name!,
                                                  style: Get
                                                      .textTheme.bodyText1!
                                                      .copyWith(
                                                    color:
                                                        Get.theme.primaryColor,
                                                    fontWeight: FontWeight.bold,
                                                    fontSize: 35.sp,
                                                  ),
                                                ),
                                                const Spacer(),
                                              ],
                                            ),
                                            SizedBox(height: 3.h),
                                            Text(
                                              state.ads[index].desc!,
                                              style: Get.textTheme.bodyText1!
                                                  .copyWith(
                                                fontSize: 35.sp,
                                                color: Get.theme.primaryColor,
                                              ),
                                              overflow: TextOverflow.ellipsis,
                                              softWrap: false,
                                            ),
                                            SizedBox(height: 3.h),
                                            Text(
                                              state.ads[index].address!,
                                              style: Get.textTheme.bodyText1!
                                                  .copyWith(
                                                fontSize: 35.sp,
                                                color: Get.theme.primaryColor,
                                              ),
                                            ),
                                            SizedBox(height: 3.h),
                                            Text(
                                              state.ads[index].phone!,
                                              style: Get.textTheme.bodyText1!
                                                  .copyWith(
                                                fontSize: 35.sp,
                                                color: Get.theme.primaryColor,
                                              ),
                                            ),
                                            SizedBox(height: 10.h),
                                            // Spacer(),
                                            Row(
                                              children: [
                                                // Text(
                                                //   '${state.ads[index].cost}',
                                                //   style:
                                                //   Get.textTheme.bodyText1!.copyWith(
                                                //     color: Colors.amber,
                                                //     fontSize: 20.sp,
                                                //   ),
                                                // ),
                                                getState(
                                                    s: state.ads[index].stute!),
                                                const Spacer(),
                                                Text(
                                                  '${state.ads[index].cost}\$',
                                                  style: Get
                                                      .textTheme.bodyText1!
                                                      .copyWith(
                                                    color: Colors.amber,
                                                    fontSize: 35.sp,
                                                  ),
                                                )
                                              ],
                                            ),
                                            SizedBox(height: 10.h),
                                            // ElevatedButton(
                                            //   onPressed: () {
                                            //     Get.dialog(
                                            //       CancelDialogView(
                                            //         id: state.ads[index].id.toString(),
                                            //         name:
                                            //         state.ads[index].nameE.toString(),
                                            //       ),
                                            //       barrierDismissible: false,
                                            //     );
                                            //   },
                                            //   style: ElevatedButton.styleFrom(
                                            //       fixedSize: Size(Get.width, 40.h)),
                                            //   child: Text(
                                            //     'Cancel'.tr,
                                            //     style: Get.textTheme.bodyText1!.copyWith(
                                            //       fontWeight: FontWeight.bold,
                                            //       color: Colors.white,
                                            //     ),
                                            //   ),
                                            // )
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                );
                              },
                              separatorBuilder:
                                  (BuildContext context, int index) {
                                return Divider(
                                  thickness: 0.7.sp,
                                  color: Get.theme.primaryColor,
                                  endIndent: 50.w,
                                  indent: 50.w,
                                );
                              },
                            ),
                          );
                  }),
          ),
        ),
      ),
    );
  }
  Widget getState({required String s}) {
    print(s);
    if (s == 'Waiting') {
      return Container(
         height: 80.h,
        width: 250.w,
        decoration: BoxDecoration(
            color: Colors.amber.withOpacity(0.6),
            borderRadius: BorderRadius.circular(8.sp)),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Waiting....'.tr,
                style: Get.theme.textTheme.bodyText1!.copyWith(
                  color: Colors.black38,
                  fontSize: 30.sp,
                ),
              ),
              const Icon(
                Icons.timer,
                color: Colors.black38,
              )
            ],
          ),
        ),
      );
    } else if (s == 'Accepted') {
      return Container(
        height: 80.h,
        width: 250.w,
        decoration: BoxDecoration(
            color: Colors.green.withOpacity(0.6),
            borderRadius: BorderRadius.circular(8.sp)),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Accepted'.tr,
                style: Get.theme.textTheme.bodyText1!.copyWith(
                  color: Colors.white,
                  fontSize: 30.sp,
                ),
              ),
              Icon(
                Icons.check,
                color: Colors.white,
              )
            ],
          ),
        ),
      );
    } else {
      return Container(
         height: 80.h,
        width: 250.w,
        decoration: BoxDecoration(
            color: Colors.red.withOpacity(0.6),
            borderRadius: BorderRadius.circular(8.sp)),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.w),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Rejected'.tr,
                style: Get.theme.textTheme.bodyText1!.copyWith(
                  color: Colors.white,
                  fontSize: 30.sp,
                ),
              ),
              Icon(
                Icons.close,
                color: Colors.white,
              )
            ],
          ),
        ),
      );
    }
  }

  
}
