/// Generated by Flutter GetX Starter on 2022-10-09 19:23
import 'package:get/get.dart';

import 'ads_state.dart';

class AdsLogic extends GetxController {
  final state = AdsState();

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
