/// Generated by Flutter GetX Starter on 2022-10-09 19:23

import 'package:ejarkom/app/Ads/ads/widget/canceled_list/canceled_list_view.dart';
import 'package:ejarkom/app/Ads/ads/widget/done_list/done_list_view.dart';
import 'package:ejarkom/app/Ads/ads/widget/ready_list/ready_list_view.dart';
import 'package:ejarkom/app/Ads/ads/widget/waitting_list/waitting_list_view.dart';
import 'package:ejarkom/app/Ads/create_ads/create_ads_view.dart';
import 'package:ejarkom/utils/widgets/leading_button.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:get/get.dart';

import '../../home/logic.dart';
import '../../main/widgets/search_bar.dart';
import 'ads_logic.dart';
import 'ads_state.dart';

class AdsView extends StatefulWidget {
  @override
  _AdsViewState createState() => _AdsViewState();
}

class _AdsViewState extends State<AdsView> with TickerProviderStateMixin {
  final AdsLogic logic = Get.put(AdsLogic());
  final AdsState state = Get.find<AdsLogic>().state;

  @override
  void dispose() {
    Get.delete<AdsLogic>();
    super.dispose();
  }

  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 4, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Get.to(() => CreateAdsView());
        },
        child: Icon(Icons.add),
        backgroundColor: Colors.amber,
      ),
      appBar: AppBar(
        leading: LeadingButton(),
        title: Text(
          'My ADS',
          style: Get.textTheme.bodyText1!.copyWith(
            fontSize: 20.sp,
            color: Get.theme.primaryColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
        bottom: TabBar(
          controller: _tabController,
          tabs: <Widget>[
            Tab(
              icon: Icon(Icons.timer),
              text: 'Waitting'.tr,
            ),
            Tab(
              icon: Icon(Icons.done),
              text: 'Ready'.tr,
            ),
            Tab(
              icon: Icon(Icons.done_all),
              text: 'Finished'.tr,
            ),
            Tab(
              icon: Icon(Icons.cancel),
              text: 'Canceled'.tr,
            ),
          ],
          indicatorSize: TabBarIndicatorSize.tab,
          indicatorWeight: 4.sp,
          unselectedLabelColor: Colors.grey,
          labelColor: Colors.amber,
          indicatorColor: Colors.amber,
          unselectedLabelStyle: Get.textTheme.bodyText1!.copyWith(
            fontSize: 14.sp,
            color: Colors.grey,
            fontWeight: FontWeight.normal,
          ),
          labelStyle: Get.textTheme.bodyText1!.copyWith(
            fontSize: 16.sp,
            color: Get.theme.primaryColor,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          image: DecorationImage(
            image: AssetImage('assets/images/newb.png'),
            fit: BoxFit.fitHeight,
          ),
        ),
        height: Get.height,
        child: TabBarView(
          controller: _tabController,
          children: [
            WaittingListPage(),
            ReadyListPage(),
            DoneListPage(),
            CanceledListPage(),
          ],
        ),
      ),
    );
  }
}
