/// Generated by Flutter GetX Starter on 2022-10-19 02:14
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'update_profile_logic.dart';
import 'update_profile_state.dart';

class updateProfileView extends StatefulWidget {
  @override
  _updateProfileViewState createState() => _updateProfileViewState();
}

class _updateProfileViewState extends State<updateProfileView> {
  final updateProfileLogic logic = Get.put(updateProfileLogic());
  final updateProfileState state = Get.find<updateProfileLogic>().state;

  @override
  void dispose() {
    Get.delete<updateProfileLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}