/// Generated by Flutter GetX Starter on 2022-10-19 02:14
import 'package:get/get.dart';

import 'update_profile_state.dart';

class updateProfileLogic extends GetxController {
  final state = updateProfileState();

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}