/// Generated by Flutter GetX Starter on 2022-10-11 23:50
import 'package:ejarkom/packs/all_packs/all_packs_logic.dart';
import 'package:ejarkom/packs/all_packs/all_packs_state.dart';
import 'package:ejarkom/utils/widgets/my_indicator.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

class AddPackView extends StatelessWidget {
  final AllPacksLogic logic = Get.find<AllPacksLogic>();

  final AllPacksState state = Get.find<AllPacksLogic>().state;
  late String id;

  AddPackView(this.id);

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      return AlertDialog(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8.sp),
        ),
        title: Row(
          children: [
            IconButton(
              onPressed: state.addPackState.value
                  ? null
                  : () {
                      Get.back();
                    },
              icon: Icon(Icons.close),
            )
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            state.addPackState.value
                ? MyIndicator()
                : Text(
                    'Are you sure you want buy this package?'.tr,
                    style: Get.textTheme.bodyText1,
                  )
          ],
        ),
        actions: [
          ButtonBar(
            children: [
              TextButton(
                onPressed: state.addPackState.value
                    ? null
                    : () {
                        logic.addPack(id: id);
                      },
                child: Text('Yes'.tr),
              ),
              TextButton(
                onPressed: state.addPackState.value
                    ? null
                    : () {
                        Get.back();
                      },
                child: Text('No'.tr),
              )
            ],
          )
        ],
      );
    });
  }
}
